use std::{collections::BTreeSet, io::Write, path::PathBuf};

use crate::manifest::StacksteadManifest;

use super::{
    model::{OWNERSHIP_OVERRIDE, RUNTIME_TOKEN_LABEL},
    ownership_model::ownership_model,
};

pub fn write_ownership_override(manifest: &StacksteadManifest) -> anyhow::Result<()> {
    let rendered = render_ownership_override(manifest)?;
    let path = ownership_override_path(manifest);
    let parent = path
        .parent()
        .ok_or_else(|| anyhow::anyhow!("Compose ownership override has no parent"))?;
    std::fs::create_dir_all(parent)?;
    let mut temporary = tempfile::NamedTempFile::new_in(parent)?;
    temporary.write_all(rendered.as_bytes())?;
    temporary.as_file().sync_all()?;
    temporary
        .persist(&path)
        .map_err(|error| anyhow::anyhow!("cannot replace {}: {}", path.display(), error.error))?;
    #[cfg(unix)]
    std::fs::File::open(parent)?.sync_all()?;
    Ok(())
}

pub(super) fn ownership_override_path(manifest: &StacksteadManifest) -> PathBuf {
    manifest.worktree.join(OWNERSHIP_OVERRIDE)
}

pub fn verify_ownership_override(manifest: &StacksteadManifest) -> anyhow::Result<()> {
    let path = ownership_override_path(manifest);
    let expected = render_ownership_override(manifest)?;
    let actual = std::fs::read_to_string(&path).map_err(|error| {
        anyhow::anyhow!(
            "cannot read generated Compose ownership override {}: {error}; run `stackstead repair {}`",
            path.display(),
            manifest.stackstead_id
        )
    })?;
    if actual != expected {
        anyhow::bail!(
            "generated Compose ownership override {} does not match runtime token {}; run `stackstead repair {}`",
            path.display(),
            manifest.runtime_token,
            manifest.stackstead_id
        );
    }
    Ok(())
}

pub fn ensure_service_configured(
    manifest: &StacksteadManifest,
    service: &str,
) -> anyhow::Result<()> {
    let services = ownership_model(&manifest.compose_files)?.services;
    if services.contains(service) {
        return Ok(());
    }
    anyhow::bail!(
        "Compose service `{service}` is not configured for {}; available services: {}",
        manifest.stackstead_id,
        services.into_iter().collect::<Vec<_>>().join(", ")
    )
}

pub(super) fn render_ownership_override(manifest: &StacksteadManifest) -> anyhow::Result<String> {
    let model = ownership_model(&manifest.compose_files)?;
    let labels = serde_json::json!({RUNTIME_TOKEN_LABEL: manifest.runtime_token});
    let entries = |names: &BTreeSet<String>| {
        names
            .iter()
            .map(|name| (name.clone(), serde_json::json!({"labels": labels})))
            .collect::<serde_json::Map<_, _>>()
    };
    let document = serde_json::json!({
        "services": entries(&model.services),
        "networks": entries(&model.networks),
        "volumes": entries(&model.volumes),
    });
    let mut output = String::from("# Generated by Stackstead. Do not edit by hand.\n");
    output.push_str(&serde_yaml::to_string(&document)?);
    Ok(output)
}
