use super::*;

#[test]
fn create_generates_the_durable_runtime_contract() -> anyhow::Result<()> {
    let project = Project::initialized()?;
    let manifest = project.create("feature-a")?;

    assert_eq!(manifest.kind, "StacksteadManifest");
    assert_eq!(manifest.version, "2");
    assert_eq!(manifest.project, "demo-project");
    assert_eq!(manifest.slug, "feature-a");
    assert_eq!(manifest.branch, "feature-a");
    assert_eq!(
        manifest.base,
        git(&project.repo, &["rev-parse", "main"])?.trim()
    );
    assert!(manifest.stackstead_id.starts_with("feature-a-"));
    assert_eq!(manifest.stackstead_id.len(), "feature-a-".len() + 32);
    assert_eq!(manifest.runtime_token.len(), 32);
    assert!(
        manifest
            .runtime_token
            .chars()
            .all(|character| character.is_ascii_hexdigit() && !character.is_ascii_uppercase())
    );
    assert_eq!(
        manifest.compose_project,
        format!("demo-project-{}", manifest.stackstead_id)
    );
    assert!(manifest.worktree.is_dir());
    assert!(manifest.state_dir.is_dir());
    assert!(manifest.state_dir.join("lock").is_file());
    assert!(manifest.state_dir.join("run.lock").is_file());
    assert!(manifest.manifest_path().is_file());
    assert!(manifest.pointer_file.is_file());
    assert!(manifest.env_file.is_file());
    assert!(manifest.agent_context.is_file());
    assert!(manifest.event_log.is_file());

    let persisted =
        StacksteadManifest::read(&manifest.manifest_path()).test_context("read manifest")?;
    assert_eq!(persisted.stackstead_id, manifest.stackstead_id);
    assert_eq!(persisted.ports, manifest.ports);
    assert_eq!(persisted.urls, manifest.urls);

    let pointer: StacksteadPointer = serde_json::from_slice(
        &fs::read(&manifest.pointer_file).test_context("read generated pointer")?,
    )
    .test_context("parse generated pointer")?;
    assert_eq!(pointer.kind, "StacksteadPointer");
    assert_eq!(pointer.version, "2");
    assert_eq!(pointer.stackstead_id, manifest.stackstead_id);
    assert_eq!(pointer.manifest, manifest.manifest_path());
    assert_eq!(pointer.repo_root, project.repo);
    assert_eq!(pointer.stackstead_root, manifest.stackstead_root);

    let environment = fs::read_to_string(&manifest.env_file).test_context("read generated env")?;
    assert!(environment.contains("# Generated by Stackstead. Do not edit by hand."));
    assert!(environment.contains(&format!("# Stackstead: {}", manifest.stackstead_id)));
    assert!(environment.contains(&format!("STACKSTEAD_ID={}", manifest.stackstead_id)));
    assert!(environment.contains(&format!("WEB_PORT={}", manifest.ports["web"])));
    assert!(environment.contains(&format!("POSTGRES_PORT={}", manifest.ports["postgres"])));

    let context = fs::read_to_string(&manifest.agent_context).test_context("read agent context")?;
    assert!(context.contains(&format!("# Stackstead: {}", manifest.stackstead_id)));
    assert!(context.contains(manifest.manifest_path().to_string_lossy().as_ref()));
    for command in [
        format!("stackstead inspect {}", manifest.stackstead_id),
        format!("stackstead context {} --print", manifest.stackstead_id),
        format!("stackstead logs {} --tail 200", manifest.stackstead_id),
        format!("stackstead db status {}", manifest.stackstead_id),
        format!("stackstead open {} web --print", manifest.stackstead_id),
        format!("stackstead up {}", manifest.stackstead_id),
        format!("stackstead repair {}", manifest.stackstead_id),
        format!("stackstead stop {}", manifest.stackstead_id),
        format!("stackstead destroy {} --yes", manifest.stackstead_id),
    ] {
        assert!(
            context.lines().any(|line| line == command),
            "missing exact context command: {command}"
        );
    }
    assert!(
        !context
            .lines()
            .any(|line| line == "stackstead inspect feature-a")
    );
    assert!(context.contains(&format!(
        "Endpoint: 127.0.0.1:{}",
        manifest.ports["postgres"]
    )));
    assert!(context.contains("Database: app"));
    assert!(!context.contains("postgres://app:app"));
    assert!(context.contains("runtime identity and state are isolated from peer stacksteads"));

    git(
        &manifest.worktree,
        &["check-ignore", "--quiet", ".stackstead/stackstead.json"],
    )?;
    assert!(
        git(
            &manifest.worktree,
            &["status", "--short", "--untracked-files=all"]
        )?
        .trim()
        .is_empty(),
        "generated contract appears in Git status"
    );
    assert_eq!(
        git(&project.repo, &["branch", "--list", "feature-a"])?.trim(),
        "+ feature-a"
    );
    assert_eq!(
        event_types(&manifest.event_log)?,
        [
            "create",
            "pointer_generate",
            "environment_generate",
            "context_generate"
        ]
    );
    Ok(())
}

#[test]
fn two_stacksteads_have_distinct_runtime_identity_and_state() -> anyhow::Result<()> {
    let project = Project::initialized()?;
    let first = project.create("feature-a")?;
    let second = project.create("feature-b")?;

    assert_ne!(first.stackstead_id, second.stackstead_id);
    assert_ne!(first.worktree, second.worktree);
    assert_ne!(first.stackstead_root, second.stackstead_root);
    assert_ne!(first.compose_project, second.compose_project);
    assert_ne!(first.env_file, second.env_file);
    assert_ne!(first.agent_context, second.agent_context);
    assert_ne!(first.manifest_path(), second.manifest_path());
    assert_ne!(first.pointer_file, second.pointer_file);
    let first_ports = first.ports.values().copied().collect::<BTreeSet<_>>();
    let second_ports = second.ports.values().copied().collect::<BTreeSet<_>>();
    assert!(first_ports.is_disjoint(&second_ports));
    assert_eq!(
        first.ports.keys().collect::<Vec<_>>(),
        second.ports.keys().collect::<Vec<_>>()
    );

    let assert = stackstead(&project.repo)
        .args(["ps", "--json"])
        .assert()
        .success();
    let listed: Value = serde_json::from_slice(&assert.get_output().stdout)
        .test_context("parse stackstead list")?;
    assert_eq!(listed["kind"], "StacksteadList");
    assert_eq!(listed["version"], "1");
    let listed = listed["stacksteads"]
        .as_array()
        .test_context("stackstead list items")?;
    assert_eq!(listed.len(), 2);
    assert_eq!(
        listed
            .iter()
            .filter_map(|item| item["stackstead_id"].as_str())
            .collect::<BTreeSet<_>>(),
        BTreeSet::from([first.stackstead_id.as_str(), second.stackstead_id.as_str()])
    );
    assert!(
        listed
            .iter()
            .all(|item| matches!(item["runtime"].as_str(), Some("stopped" | "unknown")))
    );
    Ok(())
}

#[cfg(unix)]
#[test]
fn adopted_worktree_is_bound_but_preserved_on_destroy() -> anyhow::Result<()> {
    let project = Project::initialized()?;
    let external = project
        .repo
        .parent()
        .test_context("repository has parent")?
        .join("manager-owned");
    git(
        &project.repo,
        &[
            "worktree",
            "add",
            "-b",
            "manager-feature",
            external.to_str().test_context("UTF-8 fixture path")?,
            "main",
        ],
    )?;
    let adopted = stackstead(&project.repo)
        .args([
            "--json",
            "adopt",
            "manager-feature",
            "--worktree",
            external.to_str().test_context("UTF-8 fixture path")?,
        ])
        .assert()
        .success();
    let manifest = changed_manifest(&adopted.get_output().stdout, "adopted")?;
    assert_eq!(manifest.source_ownership, SourceOwnership::External);
    assert_eq!(manifest.worktree, external);
    assert!(manifest.pointer_file.is_file());

    stackstead(&project.repo)
        .arg("adopt")
        .arg("duplicate-manager-feature")
        .arg("--worktree")
        .arg(&external)
        .assert()
        .failure();

    assert!(manifest.pointer_file.is_file());
    assert!(manifest.manifest_path().is_file());

    let path = fake_docker_path(
        project.repo.parent().test()?,
        "adopt-fake-docker-bin",
        "#!/bin/sh\nexit 0\n",
    )?;
    stackstead(&project.repo)
        .env("PATH", path)
        .args(["destroy", "manager-feature", "--yes"])
        .assert()
        .success();

    assert!(external.is_dir(), "manager-owned worktree was removed");
    assert!(!external.join(".stackstead").exists());
    assert!(!manifest.stackstead_root.exists());
    assert_eq!(
        git(&external, &["branch", "--show-current"])?.trim(),
        "manager-feature"
    );
    Ok(())
}

#[test]
fn adoption_rejects_a_manager_worktree_that_does_not_contain_the_pinned_base() -> anyhow::Result<()>
{
    let project = Project::initialized()?;
    let external = project.repo.parent().test()?.join("stale-manager-owned");
    git(
        &project.repo,
        &[
            "worktree",
            "add",
            "-b",
            "stale-manager-feature",
            external.to_str().test()?,
            "main",
        ],
    )?;
    fs::write(project.repo.join("README.md"), "# Advanced base\n").test()?;
    git(&project.repo, &["add", "README.md"])?;
    git(
        &project.repo,
        &["commit", "-m", "advance base before adoption"],
    )?;

    let rejected = stackstead(&project.repo)
        .args(["adopt", "stale-manager-feature", "--worktree"])
        .arg(&external)
        .assert()
        .failure();
    assert!(output_text(&rejected.get_output().stderr)?.contains("not based on pinned commit"));
    assert!(!external.join(".stackstead").exists());
    assert!(state_stackstead_directories(&project)?.is_empty());
    Ok(())
}

#[test]
fn adoption_rejects_nested_unrelated_and_detached_checkouts_without_state() -> anyhow::Result<()> {
    let project = Project::initialized()?;
    let parent = project.repo.parent().test_context("repository parent")?;

    let registered = parent.join("registered-manager-worktree");
    git(
        &project.repo,
        &[
            "worktree",
            "add",
            "-b",
            "registered-manager",
            registered.to_str().test_context("UTF-8 fixture path")?,
            "main",
        ],
    )?;
    let nested = registered.join("nested");
    fs::create_dir(&nested).test_context("create nested checkout path")?;
    stackstead(&project.repo)
        .arg("adopt")
        .arg("nested")
        .arg("--worktree")
        .arg(&nested)
        .assert()
        .failure();

    let mut stale_compose = fs::read_to_string(registered.join("docker-compose.yml"))
        .test_context("read manager Compose")?;
    stale_compose.push_str("# stale manager contract\n");
    fs::write(registered.join("docker-compose.yml"), stale_compose)
        .test_context("change manager Compose contract")?;
    stackstead(&project.repo)
        .arg("adopt")
        .arg("stale-manager")
        .arg("--worktree")
        .arg(&registered)
        .assert()
        .failure();

    let unrelated = parent.join("unrelated-repository");
    fs::create_dir(&unrelated).test_context("create unrelated repository")?;
    git(&unrelated, &["init", "--initial-branch=other"])?;
    git(&unrelated, &["config", "user.name", "Stackstead Tests"])?;
    git(
        &unrelated,
        &["config", "user.email", "stackstead-tests@example.invalid"],
    )?;
    fs::write(unrelated.join("README.md"), "unrelated\n")
        .test_context("write unrelated fixture")?;
    git(&unrelated, &["add", "."])?;
    git(&unrelated, &["commit", "-m", "unrelated fixture"])?;
    stackstead(&project.repo)
        .arg("adopt")
        .arg("unrelated")
        .arg("--worktree")
        .arg(&unrelated)
        .assert()
        .failure();

    let detached = parent.join("detached-manager-worktree");
    git(
        &project.repo,
        &[
            "worktree",
            "add",
            "--detach",
            detached.to_str().test_context("UTF-8 fixture path")?,
            "main",
        ],
    )?;
    stackstead(&project.repo)
        .arg("adopt")
        .arg("detached")
        .arg("--worktree")
        .arg(&detached)
        .assert()
        .failure();

    assert!(registered.is_dir());
    assert!(unrelated.is_dir());
    assert!(detached.is_dir());
    assert!(state_stackstead_directories(&project)?.is_empty());
    assert!(!registered.join(".stackstead").exists());
    assert!(!unrelated.join(".stackstead").exists());
    assert!(!detached.join(".stackstead").exists());
    Ok(())
}

#[test]
fn create_rejects_a_compose_template_that_omits_the_durable_identity() -> anyhow::Result<()> {
    let project = Project::initialized()?;
    project.replace_config(
        "{{ project.name }}-{{ stackstead.id }}",
        "{{ project.name }}",
    )?;
    let assert = stackstead(&project.repo)
        .args(["create", "feature-a", "--json"])
        .assert()
        .failure();
    assert!(output_text(&assert.get_output().stderr)?.contains("must render the durable identity"));
    assert!(state_stackstead_directories(&project)?.is_empty());
    assert!(
        git(&project.repo, &["branch", "--list", "feature-a"])?
            .trim()
            .is_empty()
    );
    Ok(())
}

#[test]
fn nested_worktree_commands_use_the_pointer_before_the_copied_config() -> anyhow::Result<()> {
    let project = Project::initialized()?;
    let manifest = project.create("feature-a")?;
    let nested = manifest.worktree.join("scratch/deeply/nested");
    fs::create_dir_all(&nested).test_context("create nested worktree directory")?;

    let assert = stackstead(&nested)
        .args(["context", "feature-a", "--json"])
        .assert()
        .success();
    let output: Value =
        serde_json::from_slice(&assert.get_output().stdout).test_context("parse context output")?;
    assert_eq!(output["stackstead_id"], manifest.stackstead_id);
    assert_eq!(
        output["path"],
        manifest.agent_context.to_string_lossy().as_ref()
    );
    Ok(())
}

#[test]
fn pointer_state_root_cannot_normalize_to_the_filesystem_root() -> anyhow::Result<()> {
    let project = Project::initialized()?;
    let mut manifest = project.create("feature-a")?;
    let mut pointer: StacksteadPointer =
        serde_json::from_slice(&fs::read(&manifest.pointer_file).test_context("read pointer")?)
            .test_context("parse pointer")?;
    manifest.project_state_root = PathBuf::from("/tmp/..");
    pointer.project_state_root = manifest.project_state_root.clone();
    manifest
        .save_atomic()
        .test_context("write tampered manifest")?;
    fs::write(
        &manifest.pointer_file,
        serde_json::to_vec_pretty(&pointer).test_context("serialize pointer")?,
    )
    .test_context("write tampered pointer")?;

    let assert = stackstead(&manifest.worktree)
        .args(["context", "feature-a", "--json"])
        .assert()
        .failure();
    assert!(output_text(&assert.get_output().stderr)?.contains("filesystem root"));
    Ok(())
}

#[test]
fn legacy_pointer_v1_discovers_normally_and_repair_rewrites_v2() -> anyhow::Result<()> {
    let project = Project::initialized()?;
    let manifest = project.create("feature-a")?;
    let mut pointer: StacksteadPointer =
        serde_json::from_slice(&fs::read(&manifest.pointer_file).test()?).test()?;
    pointer.version = "1".into();
    fs::write(
        &manifest.pointer_file,
        serde_json::to_vec_pretty(&pointer).test()?,
    )
    .test()?;
    stackstead(&manifest.worktree)
        .args(["context", "feature-a", "--json"])
        .assert()
        .success();
    stackstead(&project.repo)
        .args(["repair", "feature-a", "--json"])
        .assert()
        .success();
    let rewritten: StacksteadPointer =
        serde_json::from_slice(&fs::read(&manifest.pointer_file).test()?).test()?;
    assert_eq!(rewritten.version, "2");
    Ok(())
}

#[test]
fn destroy_recovers_a_persisted_prepublication_create() -> anyhow::Result<()> {
    let project = Project::initialized()?;
    let mut manifest = project.create("feature-a")?;
    fs::remove_file(&manifest.pointer_file).test()?;
    fs::remove_file(&manifest.event_log).test()?;
    manifest.status.source = ComponentStatus::Created;
    manifest.save_atomic().test()?;
    stackstead(&project.repo)
        .args(["destroy", &manifest.stackstead_id, "--yes"])
        .assert()
        .success();
    assert!(!manifest.stackstead_root.exists());
    let registry: Value = serde_json::from_slice(
        &fs::read(test_state_home(&project.repo).join("stackstead/port-leases.json")).test()?,
    )
    .test()?;
    assert!(registry["leases"].as_array().test()?.is_empty());
    Ok(())
}
