use std::{collections::BTreeMap, io::Write, path::Path};

use crate::manifest::StacksteadManifest;

pub fn write_generated(
    manifest: &StacksteadManifest,
    values: &BTreeMap<String, String>,
) -> anyhow::Result<()> {
    if let Some(parent) = manifest.env_file.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let mut temporary = tempfile::NamedTempFile::new_in(
        manifest
            .env_file
            .parent()
            .ok_or_else(|| anyhow::anyhow!("env path has no parent"))?,
    )?;
    writeln!(temporary, "# Generated by Stackstead. Do not edit by hand.")?;
    writeln!(temporary, "# Stackstead: {}", manifest.stackstead_id)?;
    for (key, value) in values {
        validate_env_name(key)?;
        writeln!(temporary, "{key}={}", encode_value(value))?;
    }
    temporary.as_file().sync_all()?;
    temporary
        .persist(&manifest.env_file)
        .map_err(|error| error.error)?;
    Ok(())
}

pub fn read(path: &Path) -> anyhow::Result<BTreeMap<String, String>> {
    let mut values = BTreeMap::new();
    for line in std::fs::read_to_string(path)?.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .ok_or_else(|| anyhow::anyhow!("invalid env line for key `{line}`"))?;
        validate_env_name(key)?;
        values.insert(key.to_string(), decode_value(value)?);
    }
    Ok(values)
}

pub fn rendered(path: &Path, show_secrets: bool) -> anyhow::Result<String> {
    let values = read(path)?;
    Ok(values
        .into_iter()
        .map(|(key, value)| {
            let value = if show_secrets || !should_redact(&key, &value) {
                encode_value(&value)
            } else {
                "[REDACTED]".to_string()
            };
            format!("{key}={value}")
        })
        .collect::<Vec<_>>()
        .join("\n"))
}

pub fn redacted_summary(path: &Path) -> anyhow::Result<BTreeMap<String, String>> {
    Ok(read(path)?
        .into_iter()
        .map(|(key, value)| {
            let value = if should_redact(&key, &value) {
                "[REDACTED]".into()
            } else {
                value
            };
            (key, value)
        })
        .collect())
}

pub fn is_secret_name(name: &str) -> bool {
    let upper = name.to_ascii_uppercase();
    ["PASSWORD", "TOKEN", "SECRET", "KEY", "CREDENTIAL", "AUTH"]
        .iter()
        .any(|part| upper.contains(part))
}

pub fn should_redact(name: &str, value: &str) -> bool {
    is_secret_name(name) || has_url_credentials(value)
}

fn has_url_credentials(value: &str) -> bool {
    let Some((_, remainder)) = value.split_once("://") else {
        return false;
    };
    let authority = remainder.split(['/', '?', '#']).next().unwrap_or(remainder);
    authority
        .rsplit_once('@')
        .is_some_and(|(userinfo, host)| !userinfo.is_empty() && !host.is_empty())
}

pub fn validate_env_name(name: &str) -> anyhow::Result<()> {
    let mut characters = name.chars();
    if !characters
        .next()
        .is_some_and(|character| character == '_' || character.is_ascii_alphabetic())
        || !characters.all(|character| character == '_' || character.is_ascii_alphanumeric())
    {
        anyhow::bail!("invalid environment variable name `{name}`");
    }
    Ok(())
}

fn encode_value(value: &str) -> String {
    if value.is_empty()
        || value
            .chars()
            .any(|character| character.is_whitespace() || matches!(character, '#' | '"' | '\''))
    {
        format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        value.to_string()
    }
}

fn decode_value(value: &str) -> anyhow::Result<String> {
    if value.starts_with('"') {
        if !value.ends_with('"') || value.len() < 2 {
            anyhow::bail!("unterminated quoted env value");
        }
        Ok(value[1..value.len() - 1]
            .replace("\\\"", "\"")
            .replace("\\\\", "\\"))
    } else {
        Ok(value.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validates_names_and_redacts_secret_like_keys() {
        assert!(validate_env_name("WEB_PORT").is_ok());
        assert!(validate_env_name("9PORT").is_err());
        assert!(validate_env_name("BAD-NAME").is_err());
        assert!(is_secret_name("DATABASE_PASSWORD"));
        assert!(!is_secret_name("WEB_PORT"));
    }

    #[test]
    fn reads_and_redacts_values() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join(".env");
        std::fs::write(&path, "WEB_PORT=39000\nAPI_TOKEN=private\n").unwrap();
        let output = rendered(&path, false).unwrap();
        assert!(output.contains("WEB_PORT=39000"));
        assert!(output.contains("API_TOKEN=[REDACTED]"));
        assert!(!output.contains("private"));
    }

    #[test]
    fn redacts_credentials_in_urls_even_when_key_is_not_secret_like() {
        assert!(should_redact(
            "DATABASE_URL",
            "postgres://app:password@127.0.0.1/app"
        ));
        assert!(should_redact(
            "REMOTE_URL",
            "https://access-token@example.invalid/repo"
        ));
        assert!(!should_redact("PUBLIC_URL", "http://127.0.0.1:3000/path"));
    }
}
